# Generated by Django 4.1.1 on 2023-04-24 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2023, 4, 24, 16, 17, 40, 820340)),
        ),
    ]
