# Generated by Django 4.1.1 on 2023-04-24 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addstudent', '0005_remove_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
